apiVersion: apps/v1
kind: Deployment
metadata:
  name: day-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day-2
  template:
    metadata:
      labels:
        app: day-2
    spec:
      containers:
        - name: day-2
          image: 860082039066.dkr.ecr.ap-south-1.amazonaws.com/day2:01472ab10e11dc8c5413d85a70cce63185cfede1
          ports:
            - containerPort: 3002
