apiVersion: apps/v1
kind: Deployment
metadata:
  name: day-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day-2
  template:
    metadata:
      labels:
        app: day-2
    spec:
      containers:
        - name: day-2
          image: 860082039066.dkr.ecr.ap-south-1.amazonaws.com/test:5cff25cafb4d921884ee29ee35da03919530b681
          ports:
            - containerPort: 3002
