apiVersion: apps/v1
kind: Deployment
metadata:
  name: day-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day-2
  template:
    metadata:
      labels:
        app: day-2
    spec:
      containers:
        - name: day-2
          image: 427735392661.dkr.ecr.ap-south-1.amazonaws.com/day2:bd6be8668088e418b3bdbca28ef029e4a1cc6833
          ports:
            - containerPort: 3002
