apiVersion: apps/v1
kind: Deployment
metadata:
  name: day2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day2
  template:
    metadata:
      labels:
        app: day2
    spec:
      containers:
        - name: test
          image: 860082039066.dkr.ecr.ap-south-1.amazonaws.com/day2:dd3ad3c5bb18685388527883dc0e8e10a5effdf3
          ports:
            - containerPort: 3002
