apiVersion: apps/v1
kind: Deployment
metadata:
  name: day-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: day-2
  template:
    metadata:
      labels:
        app: day-2
    spec:
      containers:
        - name: day-2
          image: 427735392661.dkr.ecr.ap-south-1.amazonaws.com/day2:25baa9807115dce3c39fa269a565fdf6c1506b06
          ports:
            - containerPort: 3002
